name = "Shabab 2"
author = "Abdulrhman Salamah"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6da5becb8952a8624ad50ff345d4bbd1090597cf771b80b35d1643efd537f9b"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
