name = "Shabab 2"
author = "Abdulrhman Salamah"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "848b6571c52b692f1b1cf9d47e2b77b9c20391d45f888c01c33aea06cb25ec24"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
