name = "Shabab 2"
author = "Abdulrhman Salamah"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "255f2a8a60a73ea26dc8193f042c6fe6468ad6f19b8d0bedc2e5b5073d1f2dbc"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
