#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jun 18 15:05:49 PDT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Better MC - Medium
enableShaders=true
