name = "Shabab"
author = "Abdulrhman Salamah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "905ec20c4d09ba6c62ea96d8a0ce3c9cb81ee2144cd80a235205607b2e8e06b4"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
