name = "Shabab"
author = "Abdulrhman Salamah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77a8355abcab189cf72d5b0d0f7e29950ad05e4936027bcda44597d55cfdbe16"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
