name = "Shabab"
author = "Abdulrhman Salamah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a382bb428425d9de9c3efc09914d92c408addcda341a7f201e9fd184138d275"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
