# Generates docs/keybinds-shabab2.md: every keybind every mod in pack-two registers, and
# what the pack binds it to. Nothing here is hand-written - keybind IDs and their labels are
# read out of the mod jars (assets/<ns>/lang/en_us.json, keys matching "key.*"), and the
# bindings are read out of pack-two/configureddefaults/options.txt.
#
#   powershell -File tools/gen-keybinds-doc.ps1 [-ModsDir <path>]
#
# -ModsDir defaults to the installed client instance, since pack-two/mods holds packwiz
# .pw.toml pointers, not the jars themselves.
#
# Keep this file ASCII-only: Windows PowerShell 5.1 reads .ps1 as ANSI unless it has a BOM,
# so a stray em-dash here is a parse error.

param(
    [string[]]$ModsDir = @("$env:APPDATA\.minecraft\mods"),
    [string]$Options   = "$PSScriptRoot\..\pack-two\configureddefaults\options.txt",
    [string]$Out       = "$PSScriptRoot\..\docs\keybinds-shabab2.md"
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.IO.Compression.FileSystem

$DASH = [char]0x2014   # em dash, for the markdown body

# ---- 1. what the pack binds -------------------------------------------------
$bound = @{}
foreach ($line in Get-Content $Options) {
    if ($line -match '^key_(.+?):(.+)$') { $bound[$Matches[1]] = $Matches[2] }
}

function Pretty([string]$k) {
    if (-not $k) { return $null }
    if ($k -eq 'key.keyboard.unknown') { return 'unbound' }
    $p = $k -replace '^key\.keyboard\.', '' -replace '^key\.mouse\.', 'Mouse '
    $p = $p -replace '\.', ' '
    if ($p.Length -gt 0) { $p = $p.Substring(0,1).ToUpper() + $p.Substring(1) }
    return $p
}

# ---- 2. what the mods register ----------------------------------------------
$rows = @()
foreach ($dir in $ModsDir) {
    if (-not (Test-Path $dir)) { continue }
    foreach ($jar in Get-ChildItem $dir -Filter *.jar) {
        try { $z = [IO.Compression.ZipFile]::OpenRead($jar.FullName) } catch { continue }

        # display name: prefer mods.toml, fall back to the jar name
        $mod = $jar.BaseName -replace '[-_](forge|fabric|mc)?[-_]?\d.*$', ''
        $meta = $z.Entries | Where-Object { $_.FullName -eq 'META-INF/mods.toml' } | Select-Object -First 1
        if ($meta) {
            $sr = New-Object IO.StreamReader($meta.Open()); $t = $sr.ReadToEnd(); $sr.Close()
            if ($t -match '(?m)^\s*displayName\s*=\s*["'']([^"'']+)') { $mod = $Matches[1] }
        }

        foreach ($e in $z.Entries) {
            if ($e.FullName -notmatch '^assets/([^/]+)/lang/en_us\.json$') { continue }
            $ns = $Matches[1]
            if ($ns -eq 'minecraft') { continue }
            $sr = New-Object IO.StreamReader($e.Open()); $txt = $sr.ReadToEnd(); $sr.Close()
            try { $json = $txt | ConvertFrom-Json } catch { continue }
            foreach ($p in $json.PSObject.Properties) {
                $id = $p.Name
                # the binding in options.txt may or may not carry the mod's ".desc" suffix
                $key = $null
                foreach ($cand in @($id, ($id -replace '\.desc$', ''), "$id.desc")) {
                    if ($bound.ContainsKey($cand)) { $key = $bound[$cand]; break }
                }
                # A keybind is either a "key.*" translation, or any translation the pack has
                # actually bound - Xaero's, for one, names its binds "gui.xaero_*".
                if (-not $key) {
                    if ($id -notlike 'key.*') { continue }
                    if ($id -like 'key.categories.*') { continue }   # category headers, not binds
                    if ($id -like '*.category') { continue }
                }
                $rows += [pscustomobject]@{
                    Mod   = $mod
                    Id    = $id
                    Label = $p.Value
                    Key   = $key
                }
            }
        }
        $z.Dispose()
    }
}

$rows = $rows | Sort-Object Mod, Id -Unique

# ---- 3. conflicts: one physical key claimed by two different actions ---------
$conflicts = $rows |
    Where-Object { $_.Key -and $_.Key -ne 'key.keyboard.unknown' } |
    Group-Object Key |
    Where-Object { $_.Count -gt 1 }

# ---- 4. write the doc --------------------------------------------------------
$md = New-Object Text.StringBuilder
$null = $md.AppendLine("# Shabab 2 $DASH Keybinds by Mod")
$null = $md.AppendLine()
$null = $md.AppendLine("Generated by ``tools/gen-keybinds-doc.ps1``. Every keybind below is read out of the mod jars")
$null = $md.AppendLine("themselves; the **Key** column is what ``pack-two/configureddefaults/options.txt`` presets on a")
$null = $md.AppendLine("fresh install. Rebinding in-game always wins $DASH the preset is only applied when a player has")
$null = $md.AppendLine("no ``options.txt`` yet.")
$null = $md.AppendLine()
$null = $md.AppendLine(("**{0} keybinds across {1} mods.** {2} are preset by the pack; the rest keep the mod's own default." -f `
    $rows.Count, ($rows | Select-Object -Expand Mod -Unique).Count, ($rows | Where-Object { $_.Key }).Count))
$null = $md.AppendLine()
$null = $md.AppendLine("- *unbound* = deliberately cleared, because the action is reachable another way.")
$null = $md.AppendLine("- *mod default* = the pack does not preset it, so whatever the mod ships with applies.")
$null = $md.AppendLine()

foreach ($g in ($rows | Group-Object Mod | Sort-Object Name)) {
    $null = $md.AppendLine("## $($g.Name)")
    $null = $md.AppendLine()
    $null = $md.AppendLine("| Key | Action | Keybind ID |")
    $null = $md.AppendLine("|---|---|---|")
    foreach ($r in ($g.Group | Sort-Object { if ($_.Key) { 0 } else { 1 } }, Label)) {
        $k = if ($r.Key) { Pretty $r.Key } else { "mod default" }
        if ($k -eq 'unbound' -or $k -eq 'mod default') { $k = "*$k*" } else { $k = "``$k``" }
        $null = $md.AppendLine(("| {0} | {1} | ``{2}`` |" -f $k, $r.Label, $r.Id))
    }
    $null = $md.AppendLine()
}

if ($conflicts) {
    $null = $md.AppendLine("## Shared keys")
    $null = $md.AppendLine()
    $null = $md.AppendLine("These physical keys are preset for more than one action. Most are harmless because the actions")
    $null = $md.AppendLine("live in different contexts (JEI's keys only fire inside a GUI, for instance), but Minecraft")
    $null = $md.AppendLine("still paints them red in the controls screen.")
    $null = $md.AppendLine()
    $null = $md.AppendLine("| Key | Claimed by |")
    $null = $md.AppendLine("|---|---|")
    foreach ($c in ($conflicts | Sort-Object Name)) {
        $who = ($c.Group | ForEach-Object { "$($_.Label) *($($_.Mod))*" }) -join " / "
        $null = $md.AppendLine(("| ``{0}`` | {1} |" -f (Pretty $c.Name), $who))
    }
    $null = $md.AppendLine()
}

$outDir = Split-Path $Out
New-Item -ItemType Directory -Force $outDir | Out-Null
$enc = New-Object Text.UTF8Encoding($false)
[IO.File]::WriteAllText((Join-Path (Resolve-Path $outDir) (Split-Path $Out -Leaf)), $md.ToString(), $enc)

Write-Host ("{0} keybinds / {1} mods / {2} preset / {3} shared keys -> {4}" -f `
    $rows.Count,
    ($rows | Select-Object -Expand Mod -Unique).Count,
    ($rows | Where-Object { $_.Key }).Count,
    @($conflicts).Count,
    $Out)
